# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_title', models.CharField(max_length=50)),
                ('cooking_time', models.CharField(max_length=20)),
                ('ingredients', models.CharField(max_length=500)),
                ('directions', models.CharField(max_length=1000)),
                ('dish_photo', models.FileField(upload_to=b'')),
            ],
        ),
    ]
