# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id1', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id2', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'friends',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
